#!/usr/bin/env bash
# Runs ON a fresh Ubuntu server (streamed in via util/run-remote.sh). Builds the load
# binaries, runs throughput/latency/WASM probes, and assembles a docs/load.md report.
# Required env: REPO, BRANCH. (ARGS is forwarded by the workflow but currently unused.)
set -euo pipefail

# Install dependencies
apt-get update -qq
apt-get install -y -qq build-essential pkg-config libssl-dev git curl protobuf-compiler

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q

# Clone repository
git clone --branch "$BRANCH" --depth 1 "https://github.com/$REPO.git" /root/roda-ledger
cd /root/roda-ledger

# Build the load binaries once, then run each directly so the captured
# output is clean (no cargo build noise leaks into the report).
echo "::group::Build"
/root/.cargo/bin/cargo build --package ledger --release \
  --bin load --bin load_latency --bin load_wasm
echo "::endgroup::"

BIN=/root/roda-ledger/target/release

# 1) Throughput — built-in deposit
echo "::group::Throughput (load)"
"$BIN/load" | tee /root/out-load.txt
echo "::endgroup::"

# 2) End-to-end latency under load, one run per wait level
for lvl in compute write commit snapshot; do
  echo "::group::Latency — wait-level=$lvl"
  "$BIN/load_latency" --wait-level "$lvl" | tee "/root/out-latency-$lvl.txt"
  echo "::endgroup::"
done

# 3) WASM deposit throughput — same deposit via Operation::Function
echo "::group::WASM deposit throughput (load_wasm)"
"$BIN/load_wasm" | tee /root/out-wasm.txt
echo "::endgroup::"

# 4) Assemble a docs/load.md-shaped report from the captured output
echo "::group::Assemble load.md"
{
  echo "# Load Test Report"
  echo
  echo "Generated by the **Load Test** workflow on a CCX33 server (Hetzner, 8 dedicated vCPU), 1,000,000 accounts, deposit operations, release build with WAL persistence enabled."
  echo
  echo "- **Throughput** — sustained tx/s with submit-side latency (\`load\`)."
  echo "- **Latency under load** — end-to-end latency to each pipeline stage (\`load_latency --wait-level\`)."
  echo "- **WASM deposit throughput** — the same deposit driven through a registered WASM function (\`load_wasm\`)."
  echo
  echo "## Throughput"
  echo
  echo '```text'
  cat /root/out-load.txt
  echo '```'
  echo
  echo "## Latency Under Load"
  echo
  echo "Each probe submits one deposit and times it until the selected pipeline index reaches it, repeated 1000x per scenario across five load levels. \`--wait-level\` picks the stage:"
  echo
  echo "| Level | Stage |"
  echo "|---|---|"
  echo "| compute | executed by the transactor (in-memory) |"
  echo "| write | written to the WAL page cache (buffered, pre-fsync) |"
  echo "| commit | fdatasync'd to disk — durable |"
  echo "| snapshot | applied to the snapshot/indexer — readable |"
  for lvl in compute write commit snapshot; do
    echo
    echo "### wait-level: $lvl"
    echo
    echo '```text'
    cat "/root/out-latency-$lvl.txt"
    echo '```'
  done
  echo
  echo "## WASM Deposit Throughput"
  echo
  echo "The deposit executed as a registered WASM \`Operation::Function\` instead of the built-in op; the gap vs Throughput above is the WASM invocation cost."
  echo
  echo '```text'
  cat /root/out-wasm.txt
  echo '```'
} > /root/load.md
echo "::endgroup::"
